### ISSUE TITLE
include img alt text in photo property

### ISSUE THREAD

**Issue by kartikprabhu** [kartikprabhu/mf2py#56]
Originally by @snarfed

https://github.com/tommorris/mf2py/issues/83

**Comment by kartikprabhu** [comment]
only relevant while parsing `u-photo`; `p-photp` will pick up the `alt` and not the `url` anyway.

Major change so for version 2.0.0 (if it goes into spec). Put under a flag for now `alt_in_photo` ?

@snarfed any "better" suggestions for the flag name?

**Comment by snarfed** [comment]
thanks! nah, i'm agreeable.

**Comment by snarfed** [comment]
however, i'd _strongly_ encourage standardizing on microformats/mf2py for issues and turn them off here. 😄  tracking issues across multiple repos is a recipe for confusion and skew.

**Comment by snarfed** [comment]
right, i understand...but they're still public, and some are duplicated, and some will skew, all of which confuses readers.

take notes for memory on the main repo issues! totally appropriate. notes are useful for other people too, collaboration and all. no one will complain. 😁
